services:
  api:
    build: .
      # context: .
      # dockerfile: Dockerfile
    container_name: node-api

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      NODE_ENV: production
      
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    # # command: npm run dev
    # command: npm start

