apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo-api-service
  labels:
    app: kubernetes-demo-api
spec:
  selector:
    app: kubernetes-demo-api
  ports:
    - protocol: TCP
      port: 3000 #service port
      targetPort: 3000 # container port
  type: NodePort #change to LoadBalancer if cloud 

